package:
  name: cavpp_pbcore_tools
  version: 0.1.4b18

source:
  git_tag: 0.1.4b18
  git_url: https://github.com/cavpp/PBCore.git

build:
  number: 2
  string: b
  osx_is_app: False
  entry_points:
    -  makepbcore = PBCore.scripts.pbcore_csv:main

requirements:
  build:
    - python
    - setuptools
    - pymediainfo
    - lxml
    - onesheet >=0.1.5

  run:
    - python
    - lxml
    - pymediainfo
    - onesheet >=0.1.5

test:
  imports:
    - PBCore.scripts.modules.PBCore
    - pymediainfo

  commands:
    - makepbcore -h
    - ffprobe -L




about:
  home: https://github.com/cavpp/audio_convert
  license: GLP
  summary: "Generates PBCore xml files from data exported from CONTENTdm and derives technical metadata from any data files that are located in the same folder."

app:
  entry: makepbcore -g
  summary: Generates PBCore xml files from data exported from CONTENTdm and derives technical metadata from any data files that are located in the same folder.
