package:
  name: cavpp_pbcore_tools
  version: 0.1.6

source:
  git_tag: 0.1.6
  git_url: https://github.com/cavpp/PBCore.git

build:
  number: 1
  string: a
  entry_points:
    -  makepbcore = PBCore.scripts.pbcore_csv:main

requirements:
  build:
    - python
    - setuptools
    - pymediainfo
    - lxml
    - onesheet >=0.1.5.7

  run:
    - python
    - lxml
    - pymediainfo
    - onesheet >=0.1.5.7

test:
  imports:
    - PBCore.scripts.modules.PBCore
    - pymediainfo

  commands:
    - makepbcore -h
    - ffprobe -L




about:
  home: https://github.com/cavpp/audio_convert
  license: GPL
  summary: "Generates PBCore xml files from data exported from CONTENTdm and derives technical metadata from any data files that are located in the same folder."

app:
  entry: makepbcore -g
  summary: Generates PBCore xml files from data exported from CONTENTdm and derives technical metadata from any data files that are located in the same folder.
  icon: CAVPP_PBCORE_icon.png
