package:
  name: cavpp_pbcore_tools
  version: 0.1.4b1

source:
  git_tag: 0.1.4b1	
  git_url: https://github.com/cavpp/PBCore.git

build:
  number: 1
  string: a
  entry_points:
    -  makemp3 = audio_convert.scripts.audioConvert:installed_start

requirements:
  build:
    - python
    - setuptools
    - onesheet >=0.1.4

  run:
    - python <3.0
    - onesheet >=0.1.4

test:
  imports:
    - audio_convert
    - modules.PBCore.PBCore

  commands:
    - makepbcore -h
    - ffprobe -L

about:
  home: https://github.com/cavpp/audio_convert
  license: GLP
  summary: "Generates PBCore xml files from data exported from CONTENTdm and derives technical metadata from any data files that are located in the same folder."

app:
  entry: makepbcore -g
  summary: Generates PBCore xml files from data exported from CONTENTdm and derives technical metadata from any data files that are located in the same folder.
